// Generated by tools/update_snapshot.py from the public schedule sheet. Do not edit by hand.
window.RLC_SNAPSHOT = [
  {
    "date": "2024-03-01",
    "speaker": "Simon Hirländer",
    "institution": "PLUS University of Salzburg",
    "topic": "Applied meta reinforcement learning",
    "link": ""
  },
  {
    "date": "2024-04-05",
    "speaker": "Catherine Laflamme",
    "institution": "Fraunhofer Austria",
    "topic": "Applied RL",
    "link": ""
  },
  {
    "date": "2024-05-03",
    "speaker": "Georg Schäfer",
    "institution": "Salzburg University of Applied Sciences",
    "topic": "Reinforcement Learning Applied to Mechatronic Systems",
    "link": ""
  },
  {
    "date": "2024-06-07",
    "speaker": "Marius Dinu",
    "institution": "JKU, ExtensityAI",
    "topic": "SymbolicRL - Creating AI-Workflows with Neuro-Symbolic Agents",
    "link": ""
  },
  {
    "date": "2024-07-05",
    "speaker": "Leander Grech",
    "institution": "University of Malta",
    "topic": "Quantum optimal control with RL",
    "link": "https://docs.google.com/presentation/d/1-J0Tth_Vg9swF19Q32x2pR1hA2IUfkDy9hKBpjHIn5s/edit?usp=sharing"
  },
  {
    "date": "2024-08-02",
    "speaker": "Matthew Schwab",
    "institution": "Helmholtz Jena, FSU Jena",
    "topic": "Laser Alignment Automation",
    "link": ""
  },
  {
    "date": "2024-09-06",
    "speaker": "-",
    "institution": "-",
    "topic": "-",
    "link": ""
  },
  {
    "date": "2024-10-04",
    "speaker": "Catherine Laflamme",
    "institution": "Fraunhofer Austria",
    "topic": "RL Implementation",
    "link": "https://www.google.com/url?q=https://teams.microsoft.com/l/meetup-join/19%253ameeting_M2YxMjQxNTYtMTZlYS00MDQzLTg4NjEtZGMzYTAwNTViNGY1%2540thread.v2/0?context%3D%257b%2522Tid%2522%253a%2522158a941a-576e-4e87-993d-b2eab8526e50%2522%252c%2522Oid%2522%253a%2522bd69fc33-9bc6-47a0-9bb7-c2f009c4a62e%2522%257d&sa=D&source=calendar&ust=1728137191988631&usg=AOvVaw20GE0K8LAgkBI7CaOJ4D0R"
  },
  {
    "date": "2024-11-01",
    "speaker": "Imola Fodor",
    "institution": "Electrolux",
    "topic": "Virtual model in the context of offline model-based RL",
    "link": ""
  },
  {
    "date": "2024-12-06",
    "speaker": "Leander Grech",
    "institution": "University of Malta",
    "topic": "RLQuantOpt",
    "link": ""
  },
  {
    "date": "2025-01-03",
    "speaker": "Imola, Leonard,Simon",
    "institution": "-",
    "topic": "Structured Models in RL",
    "link": ""
  },
  {
    "date": "2025-02-07",
    "speaker": "Imola, Leonard,Simon",
    "institution": "-",
    "topic": "Structured Models in RL",
    "link": ""
  },
  {
    "date": "2025-03-07",
    "speaker": "Olga Mironova",
    "institution": "PLUS University of Salzburg",
    "topic": "Advanced Beam Steering Control Techniques at CERN",
    "link": ""
  },
  {
    "date": "2025-04-11",
    "speaker": "General discuisson",
    "institution": "",
    "topic": "-",
    "link": ""
  },
  {
    "date": "2025-05-02",
    "speaker": "General discuisson",
    "institution": "-",
    "topic": "-",
    "link": ""
  },
  {
    "date": "2025-06-06",
    "speaker": "General discuisson",
    "institution": "-",
    "topic": "-",
    "link": ""
  },
  {
    "date": "2025-07-04",
    "speaker": "Leander Grech",
    "institution": "University of Malta",
    "topic": "RL for Air Traffic Management",
    "link": "https://docs.google.com/presentation/d/1Epz3yKSgnE1KOTWgBFFJi_XtrPijxYOWxYbfSgiQGXo/edit?usp=sharing"
  },
  {
    "date": "2025-08-01",
    "speaker": "Olga Mironova",
    "institution": "PLUS University of Salzburg",
    "topic": "Master thesis summary: Birdging control theory and RL on AWAKE",
    "link": ""
  },
  {
    "date": "2025-09-05",
    "speaker": "-",
    "institution": "-",
    "topic": "(Skipped due to Boot Camp)",
    "link": ""
  },
  {
    "date": "2025-10-03",
    "speaker": "Leander Grech",
    "institution": "University of Malta",
    "topic": "Autonomous Crystal Collimator Alignment using Reinforcement Learning",
    "link": "https://drive.google.com/file/d/1CQ1WWYb-Pzm5CDQlsGmJ_q8cVm63ZXiY/view?usp=sharing"
  },
  {
    "date": "2025-11-07",
    "speaker": "Birgit Hofer",
    "institution": "Technical University Graz",
    "topic": "Heat pump optimisation: finding a custom environment",
    "link": ""
  },
  {
    "date": "2025-12-05",
    "speaker": "Lea Keller",
    "institution": "University of Malta",
    "topic": "Reinforcement Learning for the Belousov–Zhabotinsky Reaction: From Oregonator Theory to MDP Formulation",
    "link": ""
  },
  {
    "date": "2026-01-09",
    "speaker": "Juan M. Montoya",
    "institution": "PLUS University of Salzburg",
    "topic": "RL for stock market",
    "link": ""
  },
  {
    "date": "2026-02-13",
    "speaker": "Adrian Scheerer",
    "institution": "no affiliation",
    "topic": "Implementing PPO from scratch: Interim progress update",
    "link": "https://github.com/adrische/Reimplementing-PPO"
  },
  {
    "date": "2026-03-06",
    "speaker": "Matthew Schwab",
    "institution": "Friedrich Schiller Uni Jena",
    "topic": "Update on RL for Laser Alignment",
    "link": ""
  },
  {
    "date": "2026-04-03",
    "speaker": "Simon Hirländer",
    "institution": "PLUS University of Salzburg",
    "topic": "Beyond Bayesian Optimisation: Why Accelerators Need Horizon-Aware RL",
    "link": ""
  },
  {
    "date": "2026-07-03",
    "speaker": "Juan M. Montoya",
    "institution": "PLUS University of Salzburg",
    "topic": "Certificated Temporal Abstraction",
    "link": ""
  },
  {
    "date": "2026-08-07",
    "speaker": "Sina Garazhian",
    "institution": "PLUS University of Salzburg",
    "topic": "HAMLET: Hamiltonian Model-based Learning with Epistemic Tubes",
    "link": ""
  },
  {
    "date": "2026-10-02",
    "speaker": "Hannes Waclawek",
    "institution": "Salzburg University of Applied Sciences",
    "topic": "Chebyshev Policies and the Mountain Car Problem - Reinforcement Learning for Low-Dimensional Control Tasks",
    "link": "https://arxiv.org/abs/2605.22305"
  }
];
