#!/usr/bin/env python3
"""Refresh js/talks.js from the public schedule sheet.

The page renders this snapshot instantly and then revalidates against the
live sheet in the browser, so the snapshot only has to be reasonably fresh.
Run after editing the sheet:  python3 tools/update_snapshot.py
"""
import json
import re
import sys
import urllib.request
from pathlib import Path

SHEET_ID = "1d9mY-ZdecDYc6HToxOdW3T8OqfTEnK07pExCXUc4NWg"
URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:json&gid=0"
OUT = Path(__file__).resolve().parent.parent / "js" / "talks.js"
MONTHS = {m: i for i, m in enumerate(
    ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"], 1)}


def cell(cells, i):
    c = cells[i] if i < len(cells) else None
    if not c:
        return ""
    v = c.get("v")
    if isinstance(v, str) and v.startswith("Date("):
        return v
    f = c.get("f")
    return str(f if f is not None else (v if v is not None else ""))


def iso_date(raw):
    raw = raw.strip()
    m = re.fullmatch(r"Date\((\d{4}),(\d{1,2}),(\d{1,2})\)", raw.replace(" ", ""))
    if m:
        y, mo, d = int(m[1]), int(m[2]) + 1, int(m[3])
        return f"{y:04d}-{mo:02d}-{d:02d}"
    m = re.fullmatch(r"(\d{1,2})\s+([A-Za-z]{3})[A-Za-z]*\.?\s+(\d{4})", raw)
    if m and m[2].lower() in MONTHS:
        return f"{int(m[3]):04d}-{MONTHS[m[2].lower()]:02d}-{int(m[1]):02d}"
    return None


def main():
    with urllib.request.urlopen(URL, timeout=30) as r:
        text = r.read().decode("utf-8")
    data = json.loads(text[text.index("{"): text.rindex("}") + 1])
    talks = []
    for row in data["table"]["rows"]:
        cells = row.get("c") or []
        date = iso_date(cell(cells, 0))
        if not date:
            continue
        talks.append({
            "date": date,
            "speaker": " ".join(cell(cells, 1).split()),
            "institution": " ".join(cell(cells, 2).split()),
            "topic": " ".join(cell(cells, 3).split()),
            "link": cell(cells, 4).strip(),
        })
    if len(talks) < 10:
        sys.exit(f"Only {len(talks)} rows parsed; refusing to overwrite {OUT}")
    body = json.dumps(talks, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// Generated by tools/update_snapshot.py from the public schedule sheet. Do not edit by hand.\n"
        f"window.RLC_SNAPSHOT = {body};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(talks)} talks to {OUT}")


if __name__ == "__main__":
    main()
